# Generated by Django 3.0.8 on 2020-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='email',
            field=models.EmailField(default='Noemail', max_length=150),
        ),
    ]
