# Generated by Django 3.0.8 on 2020-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_profile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
