# Generated by Django 3.0.8 on 2020-12-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20201126_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('url_field', models.URLField(max_length=400)),
                ('category', models.CharField(choices=[('bulk', 'bulk'), ('reduce weight', 'reduce weight'), ('healthy dessert', 'healthy dessert')], max_length=20)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
