# Generated by Django 3.0.8 on 2020-12-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='imageeees'),
        ),
    ]
