# Generated by Django 3.0.8 on 2020-12-26 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20201226_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_food',
            name='food',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
