# Generated by Django 3.0.8 on 2020-12-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_remove_profile_user_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_food',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Main_food'),
        ),
    ]
