# Generated by Django 3.0.8 on 2020-12-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_auto_20201229_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily_food',
        ),
    ]
