# Generated by Django 3.0.8 on 2020-12-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_daily_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_food',
            name='date_consumed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
