# Generated by Django 3.0.8 on 2020-12-29 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_auto_20201229_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_food',
            name='date_consumed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
