# Generated by Django 3.0.8 on 2021-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_auto_20210102_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_food',
            name='picture',
            field=models.ImageField(default='gallery/food-1.jpg', upload_to='gallery/food-list'),
        ),
    ]
