# Generated by Django 3.0.8 on 2021-01-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_auto_20210104_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_food',
            name='picture',
        ),
    ]
